// Module 8: Dynamic Operational Road Map Dashboard
// Real Chandigarh road geometry (OpenStreetMap) with synthetic ODD-readiness
// scoring painted onto it -- the roads are real, the scores are demo values.
// All road/scenario data is inlined here (not fetched) so index.html works
// directly over file:// with no local server.

// ROADS is entirely data-derived, not hand-picked: generated by querying
// OpenStreetMap's Overpass API for every named trunk/primary/secondary/
// tertiary way inside one fixed bounding box around central Chandigarh
// (30.715-30.760 N, 76.760-76.812 E -- matching this map's initial view),
// then chaining each road's OSM segments (which OSM splits at every
// intersection) into a single continuous path by snapping shared
// endpoints. Roads under 400m after chaining were dropped. No road name
// or coordinate here was authored by hand -- see
// docs/DASHBOARD_ROAD_DATA.md for the exact query and regeneration steps.
const ROADS = [
  { road_name: "Vidya Marg", road_type: "arterial", coords: [[30.748267,76.758649], [30.748538,76.75906], [30.749208,76.760141], [30.751446,76.763751], [30.75162,76.764017], [30.751776,76.764194], [30.752024,76.764224], [30.752161,76.764202], [30.752301,76.764099], [30.752489,76.763961], [30.754861,76.762238], [30.756398,76.761095], [30.757815,76.760012], [30.75788,76.759958], [30.75795,76.759953], [30.757917,76.760017], [30.757849,76.760068], [30.757582,76.760269], [30.757238,76.760528], [30.756426,76.761139], [30.756145,76.76135], [30.755724,76.761666], [30.755232,76.762031], [30.754902,76.762299], [30.752762,76.763879], [30.7526,76.763999], [30.752343,76.764258], [30.752253,76.764348], [30.752169,76.764492], [30.752125,76.764708], [30.752168,76.764966], [30.752202,76.765021], [30.754657,76.768911], [30.754734,76.769035], [30.755174,76.769742], [30.755195,76.769775], [30.755221,76.769817], [30.758677,76.775363], [30.758725,76.775419], [30.758827,76.775507], [30.758665,76.775657], [30.758657,76.775521], [30.758526,76.775284], [30.755147,76.769879], [30.7551,76.769804], [30.754753,76.769248], [30.75462,76.769035], [30.753153,76.766696], [30.752144,76.765067], [30.752107,76.765021], [30.751951,76.76486]] },
  { road_name: "Himalaya Marg", road_type: "arterial", coords: [[30.733678,76.779894], [30.733716,76.780063], [30.733816,76.780257], [30.734078,76.780675], [30.735237,76.782523], [30.736251,76.784143], [30.736605,76.784709], [30.736655,76.784789], [30.737112,76.785516], [30.737123,76.785533], [30.737152,76.785581], [30.737599,76.786296], [30.737715,76.786481], [30.739725,76.789693], [30.740083,76.790265], [30.740398,76.790766], [30.740485,76.790906], [30.740528,76.790975], [30.7406,76.791091], [30.74081,76.791425], [30.740993,76.79172], [30.741282,76.792186], [30.742518,76.794177], [30.742866,76.794737], [30.742793,76.794798], [30.741143,76.792146], [30.740914,76.791778], [30.740735,76.791487], [30.740525,76.791152], [30.740454,76.791038], [30.740411,76.79097], [30.740322,76.790828], [30.740011,76.790331], [30.7393,76.789196], [30.738327,76.787643], [30.737081,76.785641], [30.73705,76.785593], [30.736627,76.784927], [30.736583,76.784857], [30.735156,76.78258], [30.734499,76.781506], [30.73376,76.780299], [30.733635,76.780131], [30.733504,76.780045]] },
  { road_name: "Madhya Marg", road_type: "arterial", coords: [[30.746526,76.786161], [30.746242,76.78614], [30.746036,76.786248], [30.745544,76.786699], [30.743974,76.788023], [30.741154,76.790455], [30.741005,76.790575], [30.740606,76.790906], [30.740528,76.790975], [30.740454,76.791038], [30.74033,76.791145], [30.739998,76.79143], [30.739803,76.791597], [30.739744,76.791651], [30.737281,76.793864], [30.735366,76.795558], [30.735257,76.795654], [30.735099,76.795799], [30.734995,76.796023], [30.734858,76.79581], [30.734971,76.795767], [30.735118,76.795667], [30.73531,76.795486], [30.735716,76.79513], [30.737237,76.793797], [30.739143,76.792086], [30.739344,76.791906], [30.739596,76.79168], [30.739763,76.79153], [30.739884,76.791425], [30.740288,76.791076], [30.740411,76.79097], [30.740485,76.790906], [30.740564,76.790837], [30.740989,76.790469], [30.741118,76.790358], [30.743921,76.787932], [30.74599,76.786142], [30.746096,76.786034], [30.746206,76.785752]] },
  { road_name: "Sukhna Path", road_type: "arterial", coords: [[30.715009,76.778652], [30.715087,76.778915], [30.715182,76.779092], [30.715299,76.779311], [30.718146,76.783852], [30.718258,76.784031], [30.718445,76.784329], [30.718493,76.784406], [30.718717,76.784763], [30.721698,76.789518], [30.721893,76.789742], [30.72173,76.789892], [30.721635,76.78956], [30.720434,76.78764], [30.718758,76.78496], [30.718655,76.784795], [30.718437,76.784453], [30.718389,76.784375], [30.718201,76.784076], [30.71809,76.783898], [30.715145,76.779213], [30.715037,76.779051], [30.714917,76.778904], [30.714858,76.778851], [30.714807,76.778807]] },
  { road_name: "Udyan Path", road_type: "arterial", coords: [[30.745554,76.769111], [30.745518,76.768915], [30.745405,76.768591], [30.745265,76.76813], [30.745249,76.767474], [30.745177,76.766633], [30.745056,76.765971], [30.744985,76.765585], [30.744827,76.765043], [30.744801,76.764954], [30.744601,76.764469], [30.74431,76.763884], [30.743967,76.763279], [30.743943,76.763236], [30.743672,76.762871], [30.74326,76.762383], [30.742945,76.762053], [30.740272,76.759498], [30.739501,76.758761], [30.739458,76.758719], [30.739274,76.758588], [30.739115,76.758552], [30.739257,76.758414], [30.739438,76.758596], [30.739849,76.759012], [30.740321,76.759454], [30.741137,76.760221], [30.743002,76.761993], [30.743302,76.762317], [30.743319,76.762334], [30.743714,76.762818], [30.743989,76.763187], [30.744018,76.763237], [30.744365,76.763842], [30.744649,76.764432], [30.744863,76.764929], [30.745058,76.765569], [30.745248,76.766637], [30.745327,76.767492], [30.745341,76.768119], [30.745487,76.768554], [30.745628,76.768833], [30.745716,76.76896]] },
  { road_name: "Sarovar Path", road_type: "arterial", coords: [[30.720875,76.773639], [30.720898,76.773887], [30.721069,76.774188], [30.723791,76.778527], [30.723836,76.7786], [30.723966,76.778804], [30.724174,76.77913], [30.724261,76.779281], [30.724305,76.779352], [30.724419,76.779519], [30.727229,76.784049], [30.727272,76.784118], [30.727343,76.784232], [30.727439,76.784363], [30.727505,76.784426], [30.727597,76.784489], [30.72742,76.784623], [30.727384,76.784501], [30.727298,76.78434], [30.727243,76.784251], [30.724232,76.779409], [30.724184,76.779332], [30.723907,76.778884], [30.723767,76.778657], [30.723721,76.778584], [30.723255,76.777836], [30.722402,76.776466], [30.721849,76.775579], [30.7217,76.775341], [30.721003,76.774306], [30.720795,76.77397], [30.720735,76.773872], [30.720694,76.773831]] },
  { road_name: "Jan Marg", road_type: "arterial", coords: [[30.747116,76.785803], [30.747093,76.786031], [30.747126,76.786236], [30.74726,76.786512], [30.749456,76.790051], [30.749889,76.790738], [30.74997,76.790867], [30.75008,76.791042], [30.750264,76.791333], [30.750341,76.791455], [30.750479,76.791674], [30.753405,76.796317], [30.753584,76.796583], [30.753705,76.796764], [30.753607,76.796823], [30.753497,76.796662], [30.753397,76.796513], [30.753324,76.796406], [30.750507,76.791912], [30.750404,76.791748], [30.750261,76.791521], [30.750185,76.791399], [30.749999,76.791102], [30.749892,76.790932], [30.749808,76.790798], [30.749768,76.790735], [30.74938,76.790115], [30.747581,76.787213], [30.747169,76.786547], [30.747004,76.786349], [30.746898,76.786257], [30.746691,76.786185]] },
  { road_name: "Chandi Path", road_type: "arterial", coords: [[30.716678,76.795597], [30.716685,76.795746], [30.71676,76.795939], [30.716856,76.796144], [30.719759,76.800761], [30.719815,76.800851], [30.719942,76.801053], [30.720122,76.801338], [30.720162,76.801402], [30.720292,76.801609], [30.720439,76.801842], [30.722963,76.805857], [30.72315,76.806156], [30.723208,76.806233], [30.723281,76.80633], [30.72337,76.806436], [30.723218,76.806568], [30.723153,76.806434], [30.723063,76.806222], [30.722924,76.805998], [30.720372,76.801907], [30.720323,76.801829], [30.720096,76.801465], [30.72005,76.801391], [30.719855,76.801079], [30.719694,76.800821], [30.716909,76.796356], [30.716798,76.796178], [30.7167,76.796037], [30.716565,76.7959], [30.716429,76.795803]] },
  { road_name: "Uttar Marg", road_type: "arterial", coords: [[30.743873,76.810596], [30.743959,76.810567], [30.744038,76.810512], [30.744152,76.81041], [30.744347,76.810251], [30.744639,76.810007], [30.74472,76.809939], [30.745316,76.80944], [30.746562,76.808397], [30.747198,76.807865], [30.747356,76.807728], [30.748741,76.80657], [30.749066,76.806298], [30.749689,76.805778], [30.750021,76.805501], [30.750355,76.80522], [30.752399,76.803506], [30.752505,76.803417], [30.752756,76.803208], [30.752873,76.803108], [30.753288,76.802761], [30.753915,76.802235], [30.754914,76.801411], [30.755769,76.800706], [30.755858,76.800634], [30.756051,76.800434], [30.756168,76.800336], [30.757426,76.799277], [30.759119,76.797853], [30.759624,76.797444], [30.760164,76.796985], [30.760591,76.796622], [30.761712,76.795674]] },
  { road_name: "Dakshin Marg", road_type: "arterial", coords: [[30.73289,76.763283], [30.732688,76.763334], [30.732639,76.763346], [30.732415,76.763488], [30.73226,76.763612], [30.72824,76.766808], [30.727297,76.767641], [30.726959,76.767937], [30.726931,76.767965], [30.726823,76.768118], [30.726801,76.76815], [30.726756,76.768231], [30.726631,76.767982], [30.726859,76.767858], [30.726885,76.767841], [30.727108,76.767651], [30.727164,76.767593], [30.728208,76.766736], [30.729612,76.765597], [30.732009,76.763651], [30.732126,76.763556], [30.732273,76.763436], [30.732298,76.763415], [30.732348,76.763375], [30.732415,76.763326], [30.73255,76.763205], [30.732599,76.763152], [30.732717,76.763025]] },
  { road_name: "Udyog Path", road_type: "arterial", coords: [[30.739483,76.774668], [30.739277,76.77476], [30.73912,76.774875], [30.739078,76.774907], [30.739018,76.774951], [30.736734,76.776901], [30.736661,76.776963], [30.736317,76.777256], [30.734037,76.779202], [30.733976,76.779254], [30.733881,76.779336], [30.73377,76.779521], [30.733722,76.779678], [30.733533,76.779384], [30.733695,76.779358], [30.733855,76.77926], [30.733941,76.779187], [30.734119,76.779034], [30.734402,76.778792], [30.736101,76.77734], [30.736276,76.77719], [30.736421,76.777067], [30.73662,76.776897], [30.736692,76.776835], [30.736901,76.776657], [30.737221,76.776383], [30.738503,76.775288], [30.738997,76.774866], [30.73917,76.774654], [30.739202,76.774593], [30.739329,76.774354]] },
  { road_name: "Vigyan Path", road_type: "arterial", coords: [[30.748041,76.801652], [30.749357,76.80057], [30.749886,76.800127], [30.750299,76.799781], [30.751905,76.798437], [30.752554,76.797892], [30.752632,76.797834], [30.752691,76.797784], [30.753407,76.797176], [30.753607,76.797007], [30.753813,76.796823], [30.754496,76.796251], [30.754732,76.796054], [30.756137,76.794877], [30.75704,76.794121], [30.757338,76.793872], [30.758146,76.793195], [30.75963,76.791959], [30.759807,76.791816]] },
  { road_name: "Purv Marg", road_type: "arterial", coords: [[30.714832,76.807284], [30.715041,76.807619], [30.715089,76.807695], [30.717496,76.811544], [30.717676,76.811832], [30.717939,76.81225], [30.718007,76.812358], [30.717898,76.812469], [30.717818,76.812359], [30.717547,76.811977], [30.717403,76.811745], [30.717013,76.811114], [30.715188,76.808159], [30.714966,76.8078], [30.714917,76.807721], [30.714763,76.807471], [30.714498,76.807042], [30.71444,76.806947]] },
  { road_name: "Shanti Path", road_type: "arterial", coords: [[30.719199,76.757478], [30.719081,76.757487], [30.719007,76.757513], [30.71889,76.757595], [30.716468,76.759665], [30.714073,76.76171], [30.713941,76.761839], [30.713851,76.761953], [30.713803,76.762094], [30.713658,76.761826], [30.713733,76.761809], [30.713863,76.761745], [30.714026,76.761613], [30.716418,76.759582]] },
  { road_name: "Sector 34 Market Road", road_type: "local", coords: [[30.716992,76.767718], [30.717823,76.767015], [30.718066,76.76681], [30.718133,76.766752], [30.718192,76.766701], [30.718668,76.766308], [30.718723,76.766262], [30.719035,76.765963], [30.71942,76.765697], [30.719683,76.76562], [30.719962,76.76555], [30.720142,76.765488], [30.720258,76.765389], [30.720381,76.765316], [30.72043,76.76526], [30.720584,76.765039], [30.720755,76.764705], [30.720854,76.764482], [30.721057,76.76422], [30.721246,76.764051], [30.721302,76.763998], [30.721382,76.763948], [30.721656,76.76372], [30.721672,76.763707], [30.722544,76.76299], [30.722764,76.762799], [30.722816,76.762878], [30.72257,76.763086], [30.721708,76.763793], [30.721427,76.764015], [30.721354,76.76408], [30.721147,76.764269]] },
  { road_name: "Pashchim Marg", road_type: "arterial", coords: [[30.757849,76.760068], [30.757815,76.760012], [30.756935,76.75858], [30.756082,76.757197], [30.755331,76.755972], [30.754279,76.754269]] },
];

const SCENARIOS = {
  Clear: { visibility: [0.85, 0.95], brightness: [0.80, 0.95], traffic_density: [0.05, 0.15], wetness: [0.0, 0.1] },
  "Heavy Rain": { visibility: [0.20, 0.45], brightness: [0.30, 0.50], traffic_density: [0.30, 0.60], wetness: [0.60, 0.90] },
  "Peak Traffic": { visibility: [0.70, 0.85], brightness: [0.70, 0.85], traffic_density: [0.60, 0.90], wetness: [0.05, 0.15] },
};
const SCENARIO_NAMES = Object.keys(SCENARIOS);

function randInRange(min, max) {
  return min + Math.random() * (max - min);
}

function applyScenarioToRoad(road, scenarioName) {
  const s = SCENARIOS[scenarioName];
  road.scenario = scenarioName;
  road.visibility = randInRange(s.visibility[0], s.visibility[1]);
  road.brightness = randInRange(s.brightness[0], s.brightness[1]);
  road.traffic_density = randInRange(s.traffic_density[0], s.traffic_density[1]);
  road.wetness = randInRange(s.wetness[0], s.wetness[1]);
}

function initRoad(road) {
  applyScenarioToRoad(road, "Clear");
  road.road_quality = randInRange(0.5, 0.9);
  road.pothole_score = randInRange(0.0, 0.15);
  road.detection_confidence = randInRange(0.7, 0.95);
  return road;
}

ROADS.forEach(initRoad);

// ODD score formula, per spec.
function calculateODDScore(road) {
  let score = 100;
  score -= (1 - road.visibility) * 30;
  score -= (1 - road.brightness) * 10;
  score -= road.traffic_density * 25;
  score -= road.wetness * 15;
  score -= road.pothole_score * 10;
  score -= (1 - road.detection_confidence) * 10;
  return Math.max(0, Math.min(100, score));
}

function classifyLevel(score) {
  if (score >= 70) return { level: "L3", color: "#22c55e", label: "Full Automation" };
  if (score >= 40) return { level: "L2", color: "#f59e0b", label: "Supervised" };
  return { level: "L1", color: "#ef4444", label: "Driver Takeover" };
}

const map = L.map("map", { zoomControl: true }).setView([30.7333, 76.7794], 13);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  maxZoom: 19,
}).addTo(map);

const polylines = new Map();

function buildPopupContent(road) {
  const score = calculateODDScore(road);
  const { color, label } = classifyLevel(score);
  return `
    <div class="popup-card">
      <div class="popup-header" style="background:${color}">${road.road_name}</div>
      <div class="popup-row"><span>Type</span><span>${road.road_type}</span></div>
      <div class="popup-row"><span>Scenario</span><span>${road.scenario}</span></div>
      <div class="popup-row"><span>ODD Score</span><span>${score.toFixed(1)}</span></div>
      <div class="popup-row"><span>Automation</span><span>${label}</span></div>
      <div class="popup-row"><span>Visibility</span><span>${road.visibility.toFixed(2)}</span></div>
      <div class="popup-row"><span>Brightness</span><span>${road.brightness.toFixed(2)}</span></div>
      <div class="popup-row"><span>Traffic Density</span><span>${road.traffic_density.toFixed(2)}</span></div>
      <div class="popup-row"><span>Wetness</span><span>${road.wetness.toFixed(2)}</span></div>
      <div class="popup-row"><span>Pothole Score</span><span>${road.pothole_score.toFixed(2)}</span></div>
      <div class="popup-row"><span>Detection Conf.</span><span>${road.detection_confidence.toFixed(2)}</span></div>
      <div class="popup-row"><span>Road Quality</span><span>${road.road_quality.toFixed(2)}</span></div>
    </div>
  `;
}

function renderRoads() {
  ROADS.forEach((road) => {
    const score = calculateODDScore(road);
    const { color } = classifyLevel(score);
    const line = L.polyline(road.coords, {
      color,
      weight: 6,
      opacity: 0.85,
      lineCap: "round",
    }).addTo(map);
    line.bindPopup(buildPopupContent(road));
    polylines.set(road.road_name, line);
  });
}

function updateRoadVisual(road) {
  const score = calculateODDScore(road);
  const { color } = classifyLevel(score);
  const line = polylines.get(road.road_name);
  line.setStyle({ color });
  line.setPopupContent(buildPopupContent(road));
}

function updateCounts() {
  let l3 = 0;
  let l2 = 0;
  let l1 = 0;
  ROADS.forEach((road) => {
    const { level } = classifyLevel(calculateODDScore(road));
    if (level === "L3") l3 += 1;
    else if (level === "L2") l2 += 1;
    else l1 += 1;
  });
  document.getElementById("count-l3").textContent = l3;
  document.getElementById("count-l2").textContent = l2;
  document.getElementById("count-l1").textContent = l1;
}

function pickCluster(size) {
  const startIdx = Math.floor(Math.random() * ROADS.length);
  const cluster = [];
  for (let i = 0; i < size; i += 1) {
    cluster.push(ROADS[(startIdx + i) % ROADS.length]);
  }
  return cluster;
}

function injectScenario() {
  const scenarioName = SCENARIO_NAMES[Math.floor(Math.random() * SCENARIO_NAMES.length)];
  const clusterSize = 2 + Math.floor(Math.random() * 3); // 2-4 localized roads
  const cluster = pickCluster(clusterSize);

  cluster.forEach((road) => {
    applyScenarioToRoad(road, scenarioName);
    updateRoadVisual(road);
  });

  document.getElementById("scenario-value").textContent =
    `${scenarioName} — ${cluster.map((r) => r.road_name).join(", ")}`;

  updateCounts();
}

function renderPipelineStats() {
  const container = document.getElementById("pipeline-stats");
  if (typeof PIPELINE_STATS === "undefined") {
    return; // pipeline_stats.js not generated yet -- keep the default note.
  }

  const s = PIPELINE_STATS;
  const modeRow = (mode, cls) =>
    `<div class="count-row"><span class="dot ${cls}"></span> ${mode} <span>${s.final_mode_counts[mode] || 0}</span></div>`;

  container.innerHTML = `
    <p class="pipeline-note">${s.num_scenes} real IDD-Lite scenes processed.</p>
    ${modeRow("Normal", "dot-l3")}
    ${modeRow("Degraded", "dot-l2")}
    ${modeRow("Takeover", "dot-l1")}
    <p class="pipeline-note">Mean ODD score: ${s.mean_odd_score.toFixed(1)} / 100</p>
    <p class="pipeline-note">Automation-feasible: ${(s.fraction_automation_feasible * 100).toFixed(1)}%</p>
  `;
}

// Stage 8: Closed-Loop Simulation replay marker.
//
// closed_loop_runner.py writes one full (finished) simulation run as
// `const CARLA_LIVE = {...}` to carla_live.js (same file:// reasoning as
// PIPELINE_STATS above -- see write_carla_live_js()'s docstring). Since a
// run is a bounded, already-completed tick sequence, this replays it
// client-side with setInterval rather than polling a live server -- no
// new infrastructure, works over plain file:// like the rest of this
// dashboard. If carla_live.js hasn't been generated yet, CARLA_LIVE is
// undefined and this whole block is a silent no-op.
const CARLA_MODE_COLORS = { Normal: "#22c55e", Degraded: "#f59e0b", Takeover: "#ef4444" };

function interpolateAlongPolyline(coords, progress) {
  if (coords.length === 1) return coords[0];
  const clamped = Math.max(0, Math.min(1, progress));
  const segLengths = [];
  let total = 0;
  for (let i = 0; i < coords.length - 1; i += 1) {
    const d = L.latLng(coords[i]).distanceTo(L.latLng(coords[i + 1]));
    segLengths.push(d);
    total += d;
  }
  let target = clamped * total;
  for (let i = 0; i < segLengths.length; i += 1) {
    if (target <= segLengths[i] || i === segLengths.length - 1) {
      const t = segLengths[i] === 0 ? 0 : target / segLengths[i];
      const [lat1, lng1] = coords[i];
      const [lat2, lng2] = coords[i + 1];
      return [lat1 + (lat2 - lat1) * t, lng1 + (lng2 - lng1) * t];
    }
    target -= segLengths[i];
  }
  return coords[coords.length - 1];
}

function renderCarlaLiveStats(tick, meta) {
  const container = document.getElementById("carla-live-stats");
  if (!container) return;
  container.innerHTML = `
    <p class="pipeline-note">${meta.used_carla ? "Live CARLA server" : "Local kinematic fallback (no CARLA attached)"} — replaying ${meta.ticks.length} ticks on ${meta.road_name}.</p>
    <div class="count-row"><span class="dot" style="background:${CARLA_MODE_COLORS[tick.mode] || "#888"}"></span> Mode <span>${tick.mode}</span></div>
    <div class="count-row"><span>ADS State</span><span>${tick.ads_state}</span></div>
    <div class="count-row"><span>RSS Distance</span><span>${tick.rss_distance.toFixed(1)} m</span></div>
    <div class="count-row"><span>Stability Margin</span><span>${tick.stability_margin.toFixed(3)}</span></div>
    <div class="count-row"><span>Ego Speed</span><span>${(tick.v_ego * 3.6).toFixed(1)} km/h</span></div>
  `;
}

function initCarlaReplay() {
  if (typeof CARLA_LIVE === "undefined" || !CARLA_LIVE.ticks || CARLA_LIVE.ticks.length === 0) {
    return;
  }
  const road = ROADS.find((r) => r.road_name === CARLA_LIVE.road_name) || ROADS[0];
  const marker = L.circleMarker(road.coords[0], {
    radius: 9,
    color: "#1d4ed8",
    weight: 2,
    fillColor: "#3b82f6",
    fillOpacity: 0.9,
  }).addTo(map);

  let i = 0;
  const step = () => {
    const tick = CARLA_LIVE.ticks[i % CARLA_LIVE.ticks.length];
    const latlng = interpolateAlongPolyline(road.coords, tick.progress);
    const color = CARLA_MODE_COLORS[tick.mode] || "#3b82f6";
    marker.setLatLng(latlng);
    marker.setStyle({ fillColor: color, color: "#1d4ed8" });
    marker.bindPopup(`
      <div class="popup-card">
        <div class="popup-header" style="background:${color}">Closed-Loop Sim — tick ${tick.tick}</div>
        <div class="popup-row"><span>Mode</span><span>${tick.mode}</span></div>
        <div class="popup-row"><span>ADS State</span><span>${tick.ads_state}</span></div>
        <div class="popup-row"><span>RSS Distance</span><span>${tick.rss_distance.toFixed(1)} m</span></div>
        <div class="popup-row"><span>Stability Margin</span><span>${tick.stability_margin.toFixed(3)}</span></div>
        <div class="popup-row"><span>Ego Speed</span><span>${(tick.v_ego * 3.6).toFixed(1)} km/h</span></div>
      </div>
    `);
    renderCarlaLiveStats(tick, CARLA_LIVE);
    i += 1;
  };

  step();
  setInterval(step, 500);
}

renderRoads();
updateCounts();
renderPipelineStats();
initCarlaReplay();
document.getElementById("scenario-value").textContent = "Clear (baseline)";

setInterval(injectScenario, 5000);
