// Auto-generated by closed_loop_runner.py -- one full closed-loop simulation run.
const CARLA_LIVE = {
  "used_carla": false,
  "road_name": "Jan Marg",
  "ticks": [
    {
      "tick": 0,
      "t": 0.0,
      "mode": "Takeover",
      "ads_state": "ODD Exit Warning",
      "rss_distance": 0.7953062499999998,
      "stability_margin": 0.1339199999999999,
      "v_ego": 0.835,
      "progress": 0.0004175
    },
    {
      "tick": 1,
      "t": 0.1,
      "mode": "Takeover",
      "ads_state": "Request to Intervene",
      "rss_distance": 1.0519163906250002,
      "stability_margin": 0.02339345340297759,
      "v_ego": 1.07325,
      "progress": 0.0009541250000000001
    },
    {
      "tick": 2,
      "t": 0.2,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.5483970307591148,
      "stability_margin": 0.02750389106104137,
      "v_ego": 1.2995875000000001,
      "progress": 0.0016039187500000002
    },
    {
      "tick": 3,
      "t": 0.30000000000000004,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.6482013075517676,
      "stability_margin": 0.029932552785733688,
      "v_ego": 1.514608125,
      "progress": 0.0023612228125
    },
    {
      "tick": 4,
      "t": 0.4,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.7480115179925535,
      "stability_margin": 0.03135380463805408,
      "v_ego": 1.71887771875,
      "progress": 0.003220661671875
    },
    {
      "tick": 5,
      "t": 0.5,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.8473402410190087,
      "stability_margin": 0.03211910378169508,
      "v_ego": 1.9129338328125,
      "progress": 0.0041771285882812505
    },
    {
      "tick": 6,
      "t": 0.6000000000000001,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.945771921248848,
      "stability_margin": 0.032432341225649156,
      "v_ego": 2.097287141171875,
      "progress": 0.005225772158867188
    },
    {
      "tick": 7,
      "t": 0.7000000000000001,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.0429546449698188,
      "stability_margin": 0.03242164914781795,
      "v_ego": 2.2724227841132816,
      "progress": 0.006361983550923829
    },
    {
      "tick": 8,
      "t": 0.8,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.1385927788258576,
      "stability_margin": 0.03217266955316776,
      "v_ego": 2.4388016449076173,
      "progress": 0.007581384373377638
    },
    {
      "tick": 9,
      "t": 0.9,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.4431727917686659,
      "stability_margin": 0.031745479185652514,
      "v_ego": 2.5968615626622364,
      "progress": 0.008879815154708755
    }
  ]
};
