// Auto-generated by closed_loop_runner.py -- one full closed-loop simulation run.
const CARLA_LIVE = {
  "used_carla": false,
  "road_name": "Jan Marg",
  "ticks": [
    {
      "tick": 0,
      "t": 0.0,
      "mode": "Takeover",
      "ads_state": "ODD Exit Warning",
      "rss_distance": 0.7953062499999998,
      "stability_margin": 0.1339199999999999,
      "v_ego": 0.835,
      "progress": 0.0004175
    },
    {
      "tick": 1,
      "t": 0.1,
      "mode": "Takeover",
      "ads_state": "Request to Intervene",
      "rss_distance": 1.0519163906250002,
      "stability_margin": 0.02339345340297759,
      "v_ego": 1.07325,
      "progress": 0.0009541250000000001
    },
    {
      "tick": 2,
      "t": 0.2,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.5483970307591148,
      "stability_margin": 0.02750389106104137,
      "v_ego": 1.2995875000000001,
      "progress": 0.0016039187500000002
    },
    {
      "tick": 3,
      "t": 0.30000000000000004,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.6482013075517676,
      "stability_margin": 0.029932552785733688,
      "v_ego": 1.514608125,
      "progress": 0.0023612228125
    },
    {
      "tick": 4,
      "t": 0.4,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.7480115179925535,
      "stability_margin": 0.03135380463805408,
      "v_ego": 1.71887771875,
      "progress": 0.003220661671875
    },
    {
      "tick": 5,
      "t": 0.5,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.8473402410190087,
      "stability_margin": 0.03211910378169508,
      "v_ego": 1.9129338328125,
      "progress": 0.0041771285882812505
    },
    {
      "tick": 6,
      "t": 0.6000000000000001,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 0.945771921248848,
      "stability_margin": 0.032432341225649156,
      "v_ego": 2.097287141171875,
      "progress": 0.005225772158867188
    },
    {
      "tick": 7,
      "t": 0.7000000000000001,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.0429546449698188,
      "stability_margin": 0.03242164914781795,
      "v_ego": 2.2724227841132816,
      "progress": 0.006361983550923829
    },
    {
      "tick": 8,
      "t": 0.8,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.1385927788258576,
      "stability_margin": 0.03217266955316776,
      "v_ego": 2.4388016449076173,
      "progress": 0.007581384373377638
    },
    {
      "tick": 9,
      "t": 0.9,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.4431727917686659,
      "stability_margin": 0.031745479185652514,
      "v_ego": 2.5968615626622364,
      "progress": 0.008879815154708755
    },
    {
      "tick": 10,
      "t": 1.0,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.5540145368388512,
      "stability_margin": 0.031183862199643336,
      "v_ego": 2.7470184845291246,
      "progress": 0.010253324396973318
    },
    {
      "tick": 11,
      "t": 1.1,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.4139940202862924,
      "stability_margin": 0.03052070853217069,
      "v_ego": 2.8896675603026685,
      "progress": 0.011698158177124652
    },
    {
      "tick": 12,
      "t": 1.2000000000000002,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.501406715997418,
      "stability_margin": 0.029781321583507547,
      "v_ego": 3.025184182287535,
      "progress": 0.013210750268268418
    },
    {
      "tick": 13,
      "t": 1.3,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.5864333182422574,
      "stability_margin": 0.028985535920176844,
      "v_ego": 3.1539249731731585,
      "progress": 0.014787712754854998
    },
    {
      "tick": 14,
      "t": 1.4000000000000001,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.668999638915495,
      "stability_margin": 0.02814912612367916,
      "v_ego": 3.2762287245145005,
      "progress": 0.016425827117112247
    },
    {
      "tick": 15,
      "t": 1.5,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.7490540648629995,
      "stability_margin": 0.027284776336385208,
      "v_ego": 3.3924172882887755,
      "progress": 0.018122035761256636
    },
    {
      "tick": 16,
      "t": 1.6,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.8265645897435334,
      "stability_margin": 0.02640276787237006,
      "v_ego": 3.5027964238743365,
      "progress": 0.019873433973193806
    },
    {
      "tick": 17,
      "t": 1.7000000000000002,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.9015161736379822,
      "stability_margin": 0.025511480142181964,
      "v_ego": 3.6076566026806196,
      "progress": 0.021677262274534117
    },
    {
      "tick": 18,
      "t": 1.8,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 1.973908396532999,
      "stability_margin": 0.024617764417984772,
      "v_ego": 3.7072737725465887,
      "progress": 0.023530899160807413
    },
    {
      "tick": 19,
      "t": 1.9000000000000001,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 6.014776121903294,
      "stability_margin": 0.02372722872528993,
      "v_ego": 3.8019100839192594,
      "progress": 0.025431854202767043
    },
    {
      "tick": 20,
      "t": 2.0,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 6.2416439285706815,
      "stability_margin": 0.022844459136789202,
      "v_ego": 3.8918145797232966,
      "progress": 0.027377761492628695
    },
    {
      "tick": 21,
      "t": 2.1,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.175901879488691,
      "stability_margin": 0.021973194557737247,
      "v_ego": 3.977223850737132,
      "progress": 0.02936637341799726
    },
    {
      "tick": 22,
      "t": 2.2,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.2382767329460904,
      "stability_margin": 0.021116466815042506,
      "v_ego": 4.058362658200275,
      "progress": 0.0313955547470974
    },
    {
      "tick": 23,
      "t": 2.3000000000000003,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.2982442738560156,
      "stability_margin": 0.020276714383533817,
      "v_ego": 4.135444525290262,
      "progress": 0.033463277009742526
    },
    {
      "tick": 24,
      "t": 2.4000000000000004,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.3558555034086144,
      "stability_margin": 0.01945587574219207,
      "v_ego": 4.208672299025748,
      "progress": 0.0355676131592554
    },
    {
      "tick": 25,
      "t": 2.5,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.411165635767157,
      "stability_margin": 0.0186554667478339,
      "v_ego": 4.278238684074461,
      "progress": 0.03770673250129263
    },
    {
      "tick": 26,
      "t": 2.6,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.464233228023698,
      "stability_margin": 0.017876645292941556,
      "v_ego": 4.344326749870738,
      "progress": 0.039878895876228
    },
    {
      "tick": 27,
      "t": 2.7,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 3.0071142425260025,
      "stability_margin": 0.017120265718563954,
      "v_ego": 4.407110412377201,
      "progress": 0.0420824510824166
    },
    {
      "tick": 28,
      "t": 2.8000000000000003,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.5638872578719147,
      "stability_margin": 0.01638692487917559,
      "v_ego": 4.466754891758341,
      "progress": 0.04431582852829577
    },
    {
      "tick": 29,
      "t": 2.9000000000000004,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.6106011342445266,
      "stability_margin": 0.0156770013360073,
      "v_ego": 4.523417147170424,
      "progress": 0.04657753710188098
    },
    {
      "tick": 30,
      "t": 3.0,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.6553262634700525,
      "stability_margin": 0.014990688843082398,
      "v_ego": 4.577246289811902,
      "progress": 0.04886616024678693
    },
    {
      "tick": 31,
      "t": 3.1,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 8.252514940945552,
      "stability_margin": 0.014328025055023605,
      "v_ego": 4.628383975321307,
      "progress": 0.051180352234447585
    },
    {
      "tick": 32,
      "t": 3.2,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 8.394678746217753,
      "stability_margin": 0.01368891620628386,
      "v_ego": 4.676964776555241,
      "progress": 0.053518834622725206
    },
    {
      "tick": 33,
      "t": 3.3000000000000003,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 8.530827379875195,
      "stability_margin": 0.013073158372876342,
      "v_ego": 4.7231165377274795,
      "progress": 0.05588039289158894
    },
    {
      "tick": 34,
      "t": 3.4000000000000004,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 8.661155031180348,
      "stability_margin": 0.012480455819377706,
      "v_ego": 4.766960710841105,
      "progress": 0.05826387324700949
    },
    {
      "tick": 35,
      "t": 3.5,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 8.785856570441103,
      "stability_margin": 0.011910436848392408,
      "v_ego": 4.80861267529905,
      "progress": 0.06066817958465902
    },
    {
      "tick": 36,
      "t": 3.6,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 8.905126501883894,
      "stability_margin": 0.011362667501317342,
      "v_ego": 4.8481820415340975,
      "progress": 0.06309227060542606
    },
    {
      "tick": 37,
      "t": 3.7,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 9.019158067657973,
      "stability_margin": 0.010836663404121871,
      "v_ego": 4.885772939457393,
      "progress": 0.06553515707515477
    },
    {
      "tick": 38,
      "t": 3.8000000000000003,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.9493374001470514,
      "stability_margin": 0.010331900006986958,
      "v_ego": 4.921484292484523,
      "progress": 0.06799589922139702
    },
    {
      "tick": 39,
      "t": 3.9000000000000004,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 2.9790615506773883,
      "stability_margin": 0.009847821429807113,
      "v_ego": 4.955410077860297,
      "progress": 0.07047360426032717
    },
    {
      "tick": 40,
      "t": 4.0,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 3.0074238691787833,
      "stability_margin": 0.009383848095068925,
      "v_ego": 4.987639573967282,
      "progress": 0.07296742404731081
    },
    {
      "tick": 41,
      "t": 4.1000000000000005,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 3.03448032064167,
      "stability_margin": 0.0089393833041998,
      "v_ego": 5.018257595268918,
      "progress": 0.07547655284494527
    },
    {
      "tick": 42,
      "t": 4.2,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 9.517328998588539,
      "stability_margin": 0.008513818892143393,
      "v_ego": 5.047344715505472,
      "progress": 0.078000225202698
    },
    {
      "tick": 43,
      "t": 4.3,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 9.603835592780289,
      "stability_margin": 0.00810654007689593,
      "v_ego": 5.074977479730198,
      "progress": 0.08053771394256311
    },
    {
      "tick": 44,
      "t": 4.4,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 3.1083496901931382,
      "stability_margin": 0.007716929605430217,
      "v_ego": 5.101228605743688,
      "progress": 0.08308832824543495
    },
    {
      "tick": 45,
      "t": 4.5,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 3.130709564096067,
      "stability_margin": 0.007344371284364687,
      "v_ego": 5.126167175456503,
      "progress": 0.08565141183316322
    },
    {
      "tick": 46,
      "t": 4.6000000000000005,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 3.152018651858622,
      "stability_margin": 0.006988252972525089,
      "v_ego": 5.149858816683678,
      "progress": 0.08822634124150504
    },
    {
      "tick": 47,
      "t": 4.7,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 3.8175589854083407,
      "stability_margin": 0.006647969102891144,
      "v_ego": 5.172365875849494,
      "progress": 0.0908125241794298
    },
    {
      "tick": 48,
      "t": 4.800000000000001,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 3.1916667548076227,
      "stability_margin": 0.006322922793071867,
      "v_ego": 5.19374758205702,
      "progress": 0.0934093979704583
    },
    {
      "tick": 49,
      "t": 4.9,
      "mode": "Takeover",
      "ads_state": "Driver Performing DDT",
      "rss_distance": 10.04504207178012,
      "stability_margin": 0.006012527596212541,
      "v_ego": 5.214060202954169,
      "progress": 0.09601642807193539
    }
  ]
};
