// Auto-generated by feasibility_map.py -- real IDD-Lite pipeline results.
const PIPELINE_STATS = {
  "num_scenes": 1402,
  "final_mode_counts": {
    "Takeover": 1062,
    "Degraded": 339,
    "Normal": 1
  },
  "automation_level_counts": {
    "L2": 1373,
    "L1": 23,
    "L3": 6
  },
  "odd_region_counts": {
    "within": 701,
    "near": 490,
    "outside": 211
  },
  "mu_odd_counts": {
    "NoRain": 526,
    "HeavyRain": 507,
    "LowRain": 369
  },
  "traffic_density_counts": {
    "Low": 504,
    "Medium": 368,
    "High": 265,
    "Congested": 265
  },
  "mean_odd_score": 51.621451646251245,
  "fraction_automation_feasible": 0.24251069900142652
};
